export const mockCategories = [
  { id: '1', name: 'Fresh Produce', slug: 'fresh-produce' },
  { id: '2', name: 'Dairy', slug: 'dairy' },
  { id: '3', name: 'Bakery', slug: 'bakery' },
  { id: '4', name: 'Pantry', slug: 'pantry' },
  { id: '5', name: 'Beverages', slug: 'beverages' },
  { id: '6', name: 'Prepared Foods', slug: 'prepared-foods' },
]

export const mockProducts = [
  {
    id: '1',
    title: 'Organic Avocado',
    slug: 'organic-avocado',
    price: 4.99,
    image: null,
    category: { name: 'Fresh Produce' },
    inStock: true,
    stock: 25,
  },
  {
    id: '2',
    title: 'Organic Tomatoes',
    slug: 'organic-tomatoes',
    price: 5.49,
    image: null,
    category: { name: 'Fresh Produce' },
    inStock: true,
    stock: 30,
  },
  {
    id: '3',
    title: 'Farm Fresh Milk',
    slug: 'farm-fresh-milk',
    price: 6.99,
    image: null,
    category: { name: 'Dairy' },
    inStock: true,
    stock: 15,
  },
  {
    id: '4',
    title: 'Artisan Sourdough',
    slug: 'artisan-sourdough',
    price: 7.99,
    image: null,
    category: { name: 'Bakery' },
    inStock: true,
    stock: 12,
  },
  {
    id: '5',
    title: 'Organic Granola',
    slug: 'organic-granola',
    price: 8.49,
    image: null,
    category: { name: 'Pantry' },
    inStock: true,
    stock: 20,
  },
  {
    id: '6',
    title: 'Cold Brew Coffee',
    slug: 'cold-brew-coffee',
    price: 5.99,
    image: null,
    category: { name: 'Beverages' },
    inStock: true,
    stock: 18,
  },
]